name: WorkFlow
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
        
        
      - name: Febrero
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:

          email: alumno21.longobardi.jonathan@ipm.edu.ar


          heroku_api_key: 4d0eb871-6ade-47e8-abfc-d6689d0cc0e1


          heroku_app_name: serene-ocean-63103


          dockerfile_directory: ./ 


          dockerfile_name: Dockerfile


          docker_options: "--no-cache" 


          process_type: web
